# Generated by Django 6.0.1 on 2026-01-19 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto Por'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='bicicletas',
            field=models.ManyToManyField(blank=True, related_name='promociones', to='productos.bicicleta', verbose_name='Bicicletas Aplicables'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creada Por'),
        ),
    ]
