# Generated by Django 6.0.1 on 2026-01-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Confirmación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Confirmación de Despacho',
                'verbose_name_plural': 'Confirmaciones de Despacho',
                'ordering': ['-fecha_confirmacion'],
            },
        ),
        migrations.CreateModel(
            name='IngresoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Ingresada')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('notas', models.TextField(blank=True, verbose_name='Notas/Observaciones')),
            ],
            options={
                'verbose_name': 'Ingreso de Stock',
                'verbose_name_plural': 'Ingresos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_tipo', models.CharField(choices=[('transporte', 'Daño en Transporte'), ('almacenamiento', 'Daño en Almacenamiento'), ('defecto_fabrica', 'Defecto de Fábrica'), ('exhibicion', 'Daño en Exhibición'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Daño')),
                ('motivo_descripcion', models.TextField(verbose_name='Descripción del Daño')),
                ('foto_evidencia', models.ImageField(upload_to='productos_danados/', verbose_name='Foto de Evidencia')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Reporte')),
                ('cantidad_afectada', models.PositiveIntegerField(default=1, verbose_name='Cantidad Afectada')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('notas_resolucion', models.TextField(blank=True, verbose_name='Notas de Resolución')),
            ],
            options={
                'verbose_name': 'Producto Dañado',
                'verbose_name_plural': 'Productos Dañados',
                'ordering': ['-fecha'],
            },
        ),
    ]
