# Generated by Django 6.0.1 on 2026-01-19 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmaciondespacho',
            name='confirmado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='confirmaciondespacho',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion_despacho', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='bicicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_stock', to='productos.bicicleta', verbose_name='Bicicleta'),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='confirmado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='productodanado',
            name='bicicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_dano', to='productos.bicicleta', verbose_name='Bicicleta'),
        ),
        migrations.AddField(
            model_name='productodanado',
            name='reportado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por'),
        ),
    ]
