# Generated by Django 6.0.1 on 2026-01-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('gama', models.CharField(choices=[('media', 'Media Gama'), ('alta', 'Alta Gama')], max_length=10, verbose_name='Gama')),
                ('tipo', models.CharField(choices=[('ruta', 'Ruta'), ('mtb', 'MTB (Mountain Bike)')], max_length=10, verbose_name='Tipo')),
                ('medida_marco', models.CharField(choices=[('xs', 'XS (Extra Small)'), ('s', 'S (Small)'), ('m', 'M (Medium)'), ('l', 'L (Large)'), ('xl', 'XL (Extra Large)')], max_length=5, verbose_name='Medida del Marco')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta')),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo sugerido para cálculo de margen de ganancia', max_digits=12, verbose_name='Costo de Adquisición')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bicicletas/', verbose_name='Imagen')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Permite ocultar productos sin eliminarlos', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Bicicleta',
                'verbose_name_plural': 'Bicicletas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
